# This file is machine-generated - editing it directly is not advised

julia_version = "1.12.6"
manifest_format = "2.0"
project_hash = "c42bb6f5938a44c0ea3e76401ccd291be1199ca1"

[[deps.Artifacts]]
uuid = "56f22d72-fd6d-98f1-02f0-08ddc0907c33"
version = "1.11.0"

[[deps.QuantumKrylov]]
deps = ["Artifacts"]
path = "."
uuid = "ded8de50-d5ab-4d43-aa04-497c0da83418"
version = "0.1.0"
